config/routes.rb
Rails.application.routes.draw do

	resources :students

	get '/', to: 'students#index'

	root 'students#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord

 def self.options_for_select
  order('LOWER(name)').map { |e| [e.name, e.id] }
 end

 has_many :students
 
end

app/models/student.rb
class Student < ApplicationRecord

 filterrific :default_filter_params => { :sorted_by => 'created_at DESC' },
              :available_filters => %w[
                sorted_by
                search_query
                with_country_id
                with_created_at_gte
              ]

 belongs_to :country

 scope :search_query, lambda { |query|

  return nil  if query.blank?

  terms = query.downcase.split(/\s+/)

  terms = terms.map { |e|
    (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }

  num_or_conds = 2
  where(
    terms.map { |term|
      "(LOWER(students.first_name) LIKE ? OR LOWER(students.last_name) LIKE ?)"
    }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten
  )
}

 scope :sorted_by, lambda { |sort_option|
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^name/
    order("LOWER(students.name) #{ direction }")
  when /^email/
    order("LOWER(students.email) #{ direction }")
  when /^country/
    order("LOWER(students.country) #{ direction }")
  when /^registered_at/
    order("LOWER(students.decorated_created_at) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
}

 scope :with_country_id, lambda { |country_ids|

 where(country_id: [*country_ids])
}

 scope :with_created_at_gte, lambda { |ref_date|

 where('students.created_at >= ?', reference_time)
}

 def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Registration date (newest first)',
       'created_at_desc'],
      ['Registration date (oldest first)', 
      	'created_at_asc'],
      ['Country (a-z)', 'country_name_asc']
    ]
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 def index
   @filterrific = initialize_filterrific(
      Student,
      params[:filterrific],
      select_options: {
        sorted_by: Student.options_for_sorted_by,
        with_country_id: Country.options_for_select
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [:sorted_by, :with_country_id],
    ) or return
   @students = @filterrific.find.page(params[:page])

   respond_to do |format|
     format.html
     format.js
   end
    
   rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info students # provided by will_paginate %>
  </div>

  <table>
    <tr>
      <th><%= filterrific_sorting_link(@filterrific, :name) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :email) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :country) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :registered_at) %></th>
    </tr>
    <% students.each do |student| %>
      <tr>
        <td><%= link_to(student.full_name, student_path(student)) %></td>
        <td><%= student.email %></td>
        <td><%= student.country_name %></td>
        <td><%= student.decorated_created_at %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate students # provided by will_paginate %>

app/views/student/index.html.erb
<%= form_for_filterrific @filterrific, :remote => true html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Country
    <%= f.select(
      :with_country_id,
      @filterrific.select_options[:with_country_id],
      { include_blank: '- Any -' }
    ) %>
  </div>
  <div>
    Registered after
    <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
  partial: 'students/list',
  locals: { students: @students }
) %>

<%= f.submit 'Filter' %>
<% end %>